[package]
name = "clock"
version = "0.1.0"
edition = "2021"
authors = ["hichho"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
[[bin]]
name = "my_clock"
path = "src/bin/main.rs"
bench = false